In [1]:
import sys
sys.path.insert(0, '../')
import numpy as np
%reload_ext autoreload
%autoreload 1
%aimport allel
%aimport allel.model
%aimport allel.model.ndarray
%aimport allel.model.bcolz
allel.__version__

'0.15.2'

In [2]:
# setup an array of genotype calls
shape = n_variants, n_samples, ploidy = 50000, 1000, 2
data = np.zeros(shape, dtype='i1')
# simulate some mutations
n_alleles = n_variants * n_samples * ploidy
idx = np.random.randint(0, (n_alleles//2)-1, size=n_alleles//20)
data[:, :, 1].reshape((-1))[idx] = 1
data[:, :, 0].reshape((-1))[idx[:n_alleles//200]] = 1
g = allel.GenotypeArray(data, copy=False)

In [3]:
g

GenotypeArray((50000, 1000, 2), dtype=int8)
[[[0 0]
  [0 0]
  [0 1]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 1]
  [0 0]
  [0 0]]]

In [4]:
g.take([0, 1, 2], axis=1)

GenotypeArray((50000, 3, 2), dtype=int8)
[[[0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

In [5]:
h = g.to_haplotypes()
h

HaplotypeArray((50000, 2000), dtype=int8)
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]

In [6]:
h.take([0, 1, 2], axis=1)

HaplotypeArray((50000, 3), dtype=int8)
[[0 0 0]
 [0 0 0]
 [0 0 0]
 ..., 
 [0 0 0]
 [0 0 0]
 [0 0 0]]

In [7]:
import bcolz

In [8]:
gc = allel.GenotypeCArray(g, cparams=bcolz.cparams(cname='zlib', clevel=1))
gc

GenotypeCArray((50000, 1000, 2), int8)
  nbytes: 95.37 MB; cbytes: 9.95 MB; ratio: 9.59
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[[0 0]
  [0 0]
  [0 1]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 1]
  [0 0]
  [0 0]]]

In [9]:
gc.take([0, 1, 2], axis=1)

GenotypeCArray((50000, 3, 2), int8)
  nbytes: 292.97 KB; cbytes: 281.73 KB; ratio: 1.04
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[[0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

In [10]:
hc = gc.to_haplotypes()
hc

HaplotypeCArray((50000, 2000), int8)
  nbytes: 95.37 MB; cbytes: 9.95 MB; ratio: 9.59
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]

In [11]:
hc.take([0, 1, 2], axis=1)

HaplotypeCArray((50000, 3), int8)
  nbytes: 146.48 KB; cbytes: 256.00 KB; ratio: 0.57
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[0 0 0]
 [0 0 0]
 [0 0 0]
 ..., 
 [0 0 0]
 [0 0 0]
 [0 0 0]]

In [12]:
ac = g.count_alleles()
ac

AlleleCountsArray((50000, 2), dtype=int32)
[[1899  101]
 [1896  104]
 [1895  105]
 ..., 
 [1901   99]
 [1882  118]
 [1893  107]]

In [13]:
gac = gc.count_alleles()
gac

AlleleCountsCArray((50000, 2), int32)
  nbytes: 390.62 KB; cbytes: 288.66 KB; ratio: 1.35
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[1899  101]
 [1896  104]
 [1895  105]
 ..., 
 [1901   99]
 [1882  118]
 [1893  107]]

In [14]:
gc.is_called()

CArrayWrapper((50000, 1000), bool)
  nbytes: 47.68 MB; cbytes: 748.94 KB; ratio: 65.20
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]]

In [15]:
gc.to_n_alt()

CArrayWrapper((50000, 1000), int8)
  nbytes: 47.68 MB; cbytes: 7.68 MB; ratio: 6.21
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[[0 0 1 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 1 0 0]]

In [16]:
pos = np.unique(np.random.randint(0, 1000000, size=50000))
pos

array([    40,     92,    100, ..., 999926, 999934, 999984])

In [17]:
ref = np.random.choice([b'A', b'C', b'T', b'G'], size=pos.shape[0])
ref

array([b'C', b'G', b'C', ..., b'G', b'G', b'C'], 
      dtype='|S1')

In [18]:
alt = np.random.choice([b'A', b'C', b'T', b'G'], size=pos.shape[0])
alt

array([b'A', b'A', b'C', ..., b'A', b'G', b'G'], 
      dtype='|S1')

In [19]:
ra = np.rec.fromarrays([pos, ref, alt], names=['POS', 'REF', 'ALT'])
vtbl = allel.VariantTable(ra)
vtbl

VariantTable((48743,), dtype=[('POS', '<i8'), ('REF', 'S1'), ('ALT', 'S1')])
[(40, b'C', b'A') (92, b'G', b'A') (100, b'C', b'C') ...,
 (999926, b'G', b'A') (999934, b'G', b'G') (999984, b'C', b'G')]

In [20]:
vctbl = allel.VariantCTable(vtbl, cparams=bcolz.cparams(cname='zlib', clevel=1))
vctbl

VariantCTable((48743,), [('POS', '<i8'), ('REF', 'S1'), ('ALT', 'S1')])
  nbytes: 476.01 KB; cbytes: 551.51 KB; ratio: 0.86
  cparams := cparams(clevel=1, shuffle=True, cname='zlib')
[(40, b'C', b'A') (92, b'G', b'A') (100, b'C', b'C') ...,
 (999926, b'G', b'A') (999934, b'G', b'G') (999984, b'C', b'G')]